name: Run Python Script

on:
  schedule:
    - cron: '30 2 * * *'  # This will run every day at 2:30 AM UTC, which is 8:00 AM IST.
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        APP_LINK: ${{ secrets.APP_LINK }}
      run: |
        python main.py
